---
- name: Check if specific KB is installed on Windows
  hosts: windows
  gather_facts: no
  vars:
    kb_id: ""

  tasks:
    - name: Get list of all installed hotfixes
      win_shell: "(Get-HotFix).HotFixID"
      register: hotfix_list

    - name: Show all installed KBs (for reference)
      debug:
        var: hotfix_list.stdout_lines

    - name: Check if KB is installed
      set_fact:
        kb_found: "{{ kb_id in hotfix_list.stdout_lines }}"

    - name: Display result
      debug:
        msg: >-
          KB {{ kb_id }} is
          {{ '✅ INSTALLED' if kb_found else '❌ NOT INSTALLED' }}
