---
- name: Check if specific KB is installed on Windows
  hosts: windows
  gather_facts: no
  vars:
    kb_to_check: ""

  tasks:
    - name: Get installed hotfixes using PowerShell
      win_shell: Get-HotFix | Select-Object -ExpandProperty HotFixID
      register: hotfix_list

    - name: Show all installed KBs (for reference)
      debug:
        var: hotfix_list.stdout_lines

    - name: Check if KB is installed
      set_fact:
        kb_installed: "{{ kb_to_check in hotfix_list.stdout_lines }}"

    - name: Display result
      debug:
        msg: >
          KB {{ kb_to_check }} is
          {% if kb_installed %} ✅ INSTALLED
          {% else %} ❌ NOT INSTALLED
          {% endif %}
