---
- name: Prompt for KB number and check if it's installed
  hosts: all  # or 'winlab' if that's your group
  gather_facts: false

  vars_prompt:
    - name: kb_id
      prompt: "Enter the KB number to check (e.g., KB5011497)"
      private: no

  tasks:
    - name: Get installed hotfixes
      win_hotfix_facts:
      register: update_facts

    - name: KB found
      debug:
        msg: "{{ inventory_hostname }}: ✅ KB {{ kb_id }} is installed"
      when: kb_id in update_facts.hotfixes | map(attribute='HotFixID') | list

    - name: KB not found
      debug:
        msg: "{{ inventory_hostname }}: ❌ KB {{ kb_id }} is NOT installed"
      when: kb_id not in update_facts.hotfixes | map(attribute='HotFixID') | list
