---
- name: Check for KB patch on Windows
  hosts: windows
  gather_facts: no

  vars_prompt:
    - name: kb_number
      prompt: "Enter the KB number to check (e.g., KB5011497)"
      private: no

  tasks:

    - name: Get the hostname
      win_hostname:
      register: host_info

    - name: Check if KB is installed
      win_shell: "Get-HotFix -Id {{ kb_number }}"
      register: hotfix_check
      ignore_errors: yes

    - name: Show result if KB is found
      debug:
        msg: "✅ {{ host_info.hostname }} has {{ kb_number }}"
      when: hotfix_check.rc == 0

    - name: Show result if KB is NOT found
      debug:
        msg: "❌ {{ host_info.hostname }} does NOT have {{ kb_number }}"
      when: hotfix_check.rc != 0

