---
- name: Get uptime from a specific Windows server in inventory
  hosts: "{{ target_server }}"
  gather_facts: false

  tasks:
    - name: Get system uptime via PowerShell
      win_shell: |
        $uptime = (Get-Date) - (Get-CimInstance Win32_OperatingSystem).LastBootUpTime
        "$env:COMPUTERNAME uptime: $($uptime.Days) days, $($uptime.Hours) hrs, $($uptime.Minutes) mins"
      register: uptime_output

    - name: Show uptime
      debug:
        msg: "{{ uptime_output.stdout }}"
